#   docker compose -f docker-compose.prod.yml --env-file .env up -d --build

services:
  api:
    image: ghcr.io/CamiloMH/payments-lab-api:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
    mem_limit: 320m
    networks:
      edge:
        aliases:
          - payments-lab-api
      db:

networks:
  edge:
    external: true
  db:
    external: true
